src/core/Viewer.js
src/system/History.js

It was the case before, but it wasn't going through the `_enable` function which adds event listeners.

Add the History as enabled by default

---

src/render/RenderManager.js

Tile size from a level wasn't read if it was specified; it is now the case.
So multi resolution cubemaps are available now.

Cubemap - read tile size when levels are specified

---

src/loader/Loader.js
tools/changelog/0.9.1.md

Redesign of the HTMLAudioElement loader to solve events never fired on Microsoft Edge.

Loader audio

---

externs/lib/three.ext.js
src/render/RenderManager.js
src/render/RenderPipeline.js
src/render/background/BackgroundMeshRenderer.js
src/render/shader/ShaderChunk/worldToScreen/wts_frag_addition.glsl
src/render/shader/ShaderChunk/worldToScreen/wts_frag_wireframe.glsl

RenderManager: enable render even without background renderer
RenderPipeline: add default TexturePass when there is no background
BackgroundMeshRenderer: add extension derivatives in material for grid media
Fragment addition shader: use max alpha for correct blending without transparent background
Wireframe shader: cleanup withtout extension addition (done by WebGLProgram)
Update ThreeJS externs

Render without background feature

---

src/display/video/VideoHTML5.js

Previous iOS version was using the webkit-playsinline attribute.
Since iOS 10.X the playsinline attribute must be used instead.

Add playslinline attribute for HTMLVideoElement

---

reference/scene/scene-media-level.json
reference/scene/scene-media-options.json
src/display/video/VideoDash.js
src/display/video/VideoHTML5.js
src/media/Media.js
src/plugin/PluginEngine.js
src/system/Device.js
src/utils/URL.js
tools/changelog/0.9.1.md

Update the multi-qualities managment for Firefox, Edge, IE11 compatibility.
Fixes :
- solve the frequent timeout event on MS browsers when requesting a quality
- second try added when a video quality request is aborted due to timeout
- add a downgrade counter to force the quality change only if the video is really "freezed"
Feature :
- add a startTime option for the media into JSON configuration to be able to set the currentTime of the video on start

Video multi qualities

---

src/display/video/VideoBase.js
src/display/video/VideoDash.js
src/display/video/VideoHTML5.js

When a video was stopped (and not paused), leaving the window as trigerring the Page Visibility API (as expected), but it was playing the video again. It is not the case anymore, there was the
this._paused flag that was badly set.

Quick fix for video and page visibility

---

src/story/Story.js

When the network was slow, in WebVR, loading a new scene (apart from the default one) could trigger the reload of the previous scene. It was cause by the gaze which was already working before the background was even up.
So now, the PickingManager is stopped when loading a new scene, until readded when the background of the next scene is ready.

Fix WebVR bad scene loading

---

reference/scene/scene-events.json
reference/scene/scene.json
reference/story/story-events.json
reference/story/story.json
src/3d/Object3D.js
src/actions/Action.js
src/actions/ActionEventDispatcher.js
src/plugin/Plugin.js
src/story/Group.js
src/story/Scene.js
src/story/Story.js
tools/changelog/0.9.2.md
tools/reference/pages.json

```js
"events":
{
"onReady": "action-story-onReady",
"onGroupChange": "action-story-onGroupChange",
"onSceneLoadStart": "action-story-onSceneLoadStart",
"onSceneLoadComplete": "action-story-onSceneLoadComplete"
}
```
```js
"events":
{
"onLoadStart": "action-scene-onLoadStart",
"onLoadComplete": "action-scene-onLoadComplete",
"onUnloadStart": "action-scene-onUnloadStart",
"onUnloadComplete": "action-scene-onUnloadComplete"
}
```
Actions have now window as the default target.
ActionEventDispatcher can now re-schedule the destroy call if it is called during event dispatch.
You can test the new events with the `story-events` sample.
You can test if actions are still working with the `hotspots-states` and the `hotspots-actions` samples.
Thanks for reviewing :sunglasses:

Alps 649 scene events

---

src/render/view/ViewFlat.js

This PR solves a display problem when resizing canvas in flat view (black areas on the side). 
Validation process
- Open change_view sample
- switch to flat view
- open console and set viewer._view.current.repeatX = false
- zoom in media and move to the left bound
- resize the container and check what happens

Flat view - bug fix when resizing the canvas (displaying black areas)

---

Gruntfile.js
README.md
tools/gruntTasks/closureExport.js

Add the option when building the minified version of FORGE to keep the debug logs. By default, logs are not kept, but they can be turned on by using `grunt min:debug`.

Remove the debug logs on minification

---

src/FORGE.js
src/plugin/Plugin.js

Turn on warnings by default
Remove the warning about the plugin reset function

Rroux plugin warnings

---

reference/viewer/viewer.json
src/core/Viewer.js
src/render/RenderManager.js
src/render/view/ViewManager.js

Fix the viewer config.
Now you can acces the viewer config via viewer.config and the global main config via viewer.mainConfig.
Fix the pause and resume methods + strarts the raf after the parse of the main config.

Rroux viewer config

---

src/hotspots/HotspotAnimation.js
src/timeline/MetaAnimation.js

As reported on the forum (https://forum.forgejs.org/viewtopic.php?f=7&t=78#p241), there was a bug when switching scene with animated hotspots.
It was the fault of empty `destroy` methods, in `MetaAnimation` and `HotspotAnimation`.
Can be tested by duplicating the scene in the sample with the rabbit and the butterfly, and doing `nextScene`

Fix animated hotspots destruction

---

src/core/Viewer.js
src/render/RenderManager.js
src/render/view/ViewManager.js

- add a destroy for the ViewManager class
- remove blocking parts in the destroy of RenderManager (cf a bug on Slack)
- add the destroy of System in the Viewer destroy

Alps 816 - Missing destroy methods

---

src/camera/Camera.js

When setting camera limits in JSON config, changing scene results in a bad reinit of bounds according to view defines.
How to reproduce and understand the problem (and the fix)
- open mpeg-dash sample project
- edit the JSON config 
- add limits to the camera of scene 1: `"camera": { "fov": { "min": 90, "max": 180, "default": 90 } }`
- launch the project beginning with scene 1: http://dev/samples/projects/mpeg-dash/#second-scene&uid=scene-1
- open console and run instructions: `viewer.story.scene.uid + " -> " +  viewer.camera.fov + " [" + viewer.camera.fovMin + ", " + viewer.camera.fovMax + "]"`
- result should be as set in JSON: 
> "scene-1 -> 90 [90, 180]"
- jump to scene-0 with previous button and recall the same instructions line. Scene 0 JSON config does not override camera limits …

Alps 871 camera limits

---

src/render/background/BackgroundMeshRenderer.js
src/render/view/ViewFlat.js

Bug alps-820
Just try **multiple-media** sample, scene 3 "image-flat-scene". It was black, displaying nothing, without this code change. From now on, it should display a flat image on a plane geometry rendered by a perspective camera.

Flat media without flat view

---

src/render/background/BackgroundMeshRenderer.js
src/render/background/BackgroundRenderer.js

- setDisplayObject now update internals when mesh is not already set
- render checks if mesh exists before doing anything

BackgroundRenderer fix entering VR in equi

---

src/render/postProcessing/EffectComposer.js
src/render/postProcessing/PostProcessing.js

Add passes to FX support in JSON.
Test case: fetch dev/projects in master branch and sources in alps-renderpipeline-support-user-passes
Open FORGE/dev/projects/fx and check FX presence

RenderPipeline / Postprocessing - add support of FX passes in JSON

---

externs/forge/core.ext.js

Core viewer objects constructor takes an object with callbacks as argument.
Allowed properties are: boot, update, beforeRender and afterRender.
Extern declaration was missing beforeRender and afterRender, and it was not usable with minified version of forge.

 Fix bug: viewer callbacks minification not fully described

---

Gruntfile.js
reference/scene/scene-media-level.json
reference/scene/scene-media-source.json
src/media/Media.js
src/media/MediaStore.js
src/media/MediaTexture.js
src/story/Scene.js

Introduces a new class for multi resolution and assets management: `MediaStore`. When creating a media, the media isn't creating an `Image`, but instead a `MediaStore`, gettable from the store property of the media object.
A `get` method is available on the `MediaStore` (available itself through `viewer.story.scene.media.store`), with four parameters: the face, the level, the x and the y of the tile to get. It returns a THREE.Texture already loaded with the correct texture.
Concerning the size of the cache, we authorize for now 30Mo, which is arbitrary. Maybe in the future we can adapt this size given the system informations (but should be limited, so idk). Textures are flushed every time the max size is reached, with the oldest texture getting out first. 
There is an exception though: …

Alps 282 - Cache management for multi resolution

---

src/core/Viewer.js

Add the `onConfigCompleteLoad` event to the Viewer, which is triggered after the viewer is ready but none configuration has been loaded, to make a distinction with the `onReady` event which is triggered before the load of the config.

Alps 949 - onConfigLoadComplete viewer event

---

src/hotspots/HotspotGeometry.js

Check the points given when creating a Shape as the geometry of a hotspot. For each point following each other, we check if they aren't the same. If there are less than three points, the Shape is the default one: a square.

Alps 833 - Error on the creation of a HotspotGeometry of type shape

---

Gruntfile.js
externs/lib/w3c.gamepad-extension.ext.js
reference/controller/controller-gamepad-axis-binding-event.json
reference/controller/controller-gamepad-axis-binding.json
reference/controller/controller-gamepad-binding.json
reference/controller/controller-gamepad-button-binding-events.json
reference/controller/controller-gamepad-button-binding.json
reference/controller/controller-gamepad.json
reference/controller/controller-instance.json
reference/controller/controller-keyboard-binding.json
src/camera/Camera.js
src/controllers/ControllerGamepad.js
src/controllers/ControllerKeyboard.js
src/controllers/ControllerManager.js
src/controllers/ControllerType.js
src/core/Viewer.js
src/input/Gamepad.js
src/input/GamepadsManager.js
src/input/Keyboard.js
src/input/binding/AxisBinding.js
src/input/binding/BaseBinding.js
src/input/binding/ButtonBinding.js
src/input/binding/KeyBinding.js
tools/reference/pages.json

Following the specification (https://www.w3.org/TR/gamepad/ and https://w3c.github.io/gamepad/extensions.html), I added a gamepad interface to the list of available  controllers. It was necessary to add it to have a base for support of Oculus, Vive and maybe other controllers of gamepad type with spatial positioning in the future.
There are two new types of binding with a gamepad (a third to come later):
- on buttons, which work a lot like keys, with three events: `onDown`, `onHold`, `onUp`
- on axis, which is different but simpler to treat as there is only one action on it: `onChange`
This is a WIP, but I'm making the code visible now as it is a relatively big chunk of code.

Alps 589 - add support for gamepad controller

---

src/input/GamepadsManager.js

Check if the gamepad method is defined on GamepadsManager boot then return from the update loop of the manager if the _gamepads array is still null

Quick fix for gamepad unavailability

---

src/core/Viewer.js
src/director/Director.js
src/display/video/VideoDash.js
src/display/video/VideoHTML5.js

Two bug fixes for 0.9.3:
- fix the director's track on Firefox: it wasn't working due to some confusion between the `seeked` event of the video and the missing `seeking` one.
- fix crashing when opening in a new tab without focusing on it

Bugfixes for 0.9.3

---

externs/forge/math.ext.js
src/hotspots/HotspotAnimation.js
src/hotspots/HotspotSound.js
src/hotspots/HotspotTransform.js
src/math/Math.js
src/utils/Utils.js
test/math/Math.spec.js

Fix the coordinates conversion from spherical to cartesian. All THREE methods that were called have been deleted, and a simplier one has been added in the Math class (`sphericalToCartesian`). This method follows the simple and classic conversion (adapted in the code to the FORGE coordinates system):
```
r ∈ [0, ∞), θ ∈ [0, π], φ ∈ [0, 2π)
x = r sin(θ) cos(φ)
y = r sin(θ) sin(φ)
z = r cos(θ)
```
Also add unit testing for this method (yay unit testing now  🎉 ).

Alps 872 hotspots coordinates

---

src/hotspots/HotspotMaterial.js

There was a bug concerning the opacity of the hotspots, which was not really one in fact:
It seemed the opacity of hotspots was badly handled, but it was due to a misconfiguration of the testing case: the `transparent` property on the `material` of a hotspot was missing, thus set to `false` by default.
Meanwhile, doing this wasn't sufficient, as there were other display problems that were corrected:
- set the material side as FrontSide only for any hotspot, beside hotspots of type PLANE, which are still DoubleSide
- remove a condition on setting the transparency of a hotspot, reduced before to textured hotspot only
The resulting correct sample is as below:

Alps 1136 - Material opacity on hotspots

---

src/core/Viewer.js

Fix destroy case when you destroy the viewer the very next line after its creation.
This includes a missing _system declaration in the Viewer constructor.
I know that this is not a common use case but it makes the code robust.
This fix is related to a forum request.
Use case is:
var viewer = new FORGE.Viewer("container", "config.json");
viewer.destroy();

Fix destroy

---

reference/camera/camera.json
src/camera/Camera.js

Early implementation of the camera keep view feature.
You can add a `keep` boolean parameter to the camera configuration to test it.
Not all use cases are taken into account but it is the very first version.

Rroux camera keep

---

Gruntfile.js
externs/forge/render.ext.js
externs/lib/three.ext.js
reference/scene/scene-media-level.json
reference/scene/scene-media-limits.json
reference/scene/scene-media-range.json
reference/scene/scene-media-source.json
src/3d/Tile.js
src/camera/Camera.js
src/controllers/ControllerPointer.js
src/media/Media.js
src/media/MediaStore.js
src/media/MediaTexture.js
src/render/RenderManager.js
src/render/background/BackgroundPyramidRenderer.js
src/render/background/BackgroundRenderer.js
src/render/background/BackgroundType.js
src/render/view/ViewBase.js
src/render/view/ViewFlat.js
src/story/Scene.js
src/utils/Utils.js
test/utils/Utils.spec.js
tools/reference/pages.json

So it is finally here, the multi resolution ! After a lot of hardwork (from @ygilquin-gpsw mainly), we can now merge it in master !
Multiple things to check here :
- Introduction of the `BackgroundPyramidRenderer`, which is the main actor in the multi resolution. To provide a "good" asynchronous behavior here, some methods rely a lot upon Promises.
- Introduction of `Tile`s, which are visual components of the multi resolution, that show the according image associated to a specific level.
- Introduction of a new `Media` type, the `MediaStore`, which contains a lot of `MediaTexture`. `MediaTexture` are simpler `Image` with only a few properties, making them very light. The `MediaStore` has a cache for managing recently and not-so-recently used `MediaTexture`.
- The specification of the …

Multi resolution

---

src/system/History.js
src/utils/URL.js

Add short URL support for camera & view parameters into the generateHash method of History.
Short format sample : `&-32.02y,6.03p,0.00r,90.00f,rectilinearv` which is equivalent to `&yaw=-32.02&pitch=6.03&roll=0.00&fov=90.00&view=rectilinear`

Alps 1296 - Share current Camera & View parameters

---

src/hotspots/HotspotDOM.js

Fix #122 
When destroying a HotspotDOM, do not remove the dom but hide it away.
Adapted the events because of bad reference when destroying it.

Destroying HotspotDOM

---

src/story/Story.js

Fix the startTime of a media not taken into account: medias were always starting at 0s, unless it was synced with another media.

ALPS-1815 - startTime not respected

---

src/camera/Camera.js

The cancelRoll attribute wasn't taken in account into the Camera.lookAt method when a tween was used.

Add cancelRoll attribute for the camera lookAt method

---

src/render/view/ViewFlat.js
src/render/view/ViewGoPro.js
src/render/view/ViewRectilinear.js

Current status: if the current view is destroyed the updateViewParams method can be called from event with a nullified viewer.

Avoid the update of the view when the view is under destroy status

---

src/hotspots/HotspotMaterial.js

So that a plugin can be used as hotspot texture on multiple scenes.

Disable the destroy of the Hotspot DisplayObject object when it's a plugin

---

Gruntfile.js
README.md
tools/gruntTasks/closureExport.js

Two flags have been added, one for keeping the debug log in FORGE (--keep-log), the other
one for passing through testing (--no-test)

Change the way we can call the min grunt task.

---

src/camera/Camera.js

Set the fov first in the setAll method of the Camera (code I forgot to commit). The bug is visible when a big change of pitch is done like in the Paris sample.

ALPS-2105 - Camera Limits fix

---

src/camera/Camera.js

When we get the fov boundaries, we don't verify the yaw and pitch
boundaries if the view is flat.

Fix the camera when a view is flat.

---

src/render/RenderManager.js

Rework parse of background renderer type, hence fix a bug when two multiquality video were following each other.
Fix the problem in https://github.com/gopro/forgejs-samples/pull/44/

BackgroundRenderer Type fix

---

test/hotspots/HotspotManager.spec.js

Fix the hotspot test, caused by a forgotten update of `viewer.onReady` to `viewer.onConfigLoadComplete`.

Fix the hotspot test

---

externs/lib/three.ext.js
src/3d/Tile.js
src/camera/Camera.js
src/render/background/BackgroundPyramidRenderer.js
src/render/background/BackgroundRenderer.js

Fix some deficient use cases with multiresolution rendering.
Look somewhere in some high level and display a distant part of the scene at the same level immediately. This was not refreshing without this fix.
We reinject in the scene children of a tile that are in the viewing frustum but out of the scene. 
Additions:
Rewrite clear policy code to improve semantics and clarity
Fix display of tile debugging canvas
Add a frustum property to the background renderer

Multiresolution stabilization

---

src/hotspots/Hotspot3D.js
src/hotspots/HotspotDOM.js

Solve issues if the "display:none" property was set on a DOM hotspot and solve the issue if an other scene is called and uses the same view (which is not refreshed).

Force the display of visible DOM hotspots into a new scene
