gopro/forgejs

- src/camera/Camera.js
- src/core/Viewer.js
Add a listener on container resize for perspective camera update
> Perspective camera update

- src/render/background/BackgroundMeshRenderer.js
- src/utils/Utils.js
- tools/changelog/0.9.1.md
Polyfill for Array.prototype.keys method for Internet Explorer 11 cubemap media type management
> Polyfill array keys

- externs/lib/three.ext.js
- src/camera/Camera.js
- src/core/Viewer.js
- src/media/Media.js
- src/media/MediaType.js
- src/render/RenderManager.js
- src/render/background/BackgroundMeshRenderer.js
- src/render/background/BackgroundShaderRenderer.js
- src/render/shader/ShaderChunk/common/vert_attributes_wireframe.glsl
- src/render/shader/ShaderChunk/worldToScreen/wts_frag_wireframe.glsl
- src/render/shader/ShaderChunk/worldToScreen/wts_vert_gopro_wireframe.glsl
- src/render/shader/ShaderChunk/worldToScreen/wts_vert_rectilinear_wireframe.glsl
- src/render/shader/ShaderLib.js
- src/render/view/ViewBase.js
- src/render/view/ViewGoPro.js
- src/render/view/ViewRectilinear.js
- src/story/SceneParser.js
- tools/changelog/0.9.1.md
Replace last pull request on ygilquin-media-grid
> Ygilquin media grid clean

- src/camera/Camera.js
- src/display/components/Canvas.js
- src/story/Story.js
- tools/changelog/0.9.1.md
Just fix cammera parallax setter + add accessor on Story.js
> Rroux debug

- src/plugin/PluginEngine.js
- tools/changelog/0.9.2.md
Fix versioning check (0.0.0 to 9.9.9)
> Plugin versioning

- src/render/background/BackgroundRenderer.js
Easy access with viewer.renderer.backgroundRenderer.scene
> Add getter to access the THREE.Scene of the BackgroundRenderer

- src/display/components/TextField.js
fontWeight property usage issue
> Update types and correct fontWeight issue

- externs/forge/hotspot.ext.js
- externs/lib/three.ext.js
- reference/hotspot/hotspot-geometry.json
- src/hotspots/Hotspot3D.js
- src/hotspots/HotspotGeometry.js
- src/hotspots/HotspotGeometryType.js
Add SHAPE in geometry types and create THREE.Shape from an array of points specified in JSON config
> 3D shaped hotspots

- reference/display/sprite-animation.json
- reference/display/sprite.json
- reference/display/video.json
- reference/hotspot/hotspot-material.json
- src/display/image/Image.js
- src/display/sprite/Sprite.js
- src/display/sprite/SpriteAnimation.js
- src/display/sprite/SpriteAnimationManager.js
- src/display/video/VideoHTML5.js
- src/hotspots/Hotspot3D.js
- src/hotspots/HotspotMaterial.js
- src/render/background/BackgroundRenderer.js
- tools/changelog/0.9.2.md
- tools/reference/pages.json
Hotspot sprite material implementation.
Hotspot video material implementation.
You can test the sample hotspots-sprite.
A sample for video material is coming tomorrow.
> Alps 577 hotspot sprite

- src/media/Media.js
- src/system/Device.js
- tools/gruntTasks/closureExport.js
Refactor of the FORGE.Device singleton for the BaseObject extend
> FORGE.Device refactor

- externs/forge/camera.ext.js
- src/camera/Camera.js
- src/render/background/BackgroundMeshRenderer.js
- src/render/view/ViewBase.js
- src/render/view/ViewFlat.js
- src/render/view/ViewGoPro.js
- src/render/view/ViewManager.js
- src/render/view/ViewRectilinear.js
This PR fixes bugs 719 and 762 stored in JIRA.
> Alps 762 change view issue

- src/camera/Camera.js
- src/render/view/ViewFlat.js
- src/render/view/ViewManager.js
In replacement of the old branch that goes bad after the rebase  :skull:
> Alps 823 flat view repeat fix rroux

- externs/lib/hammer.ext.js
- reference/controller/controller-pointer.json
- src/controllers/ControllerPointer.js
Adding the double click/tap/touch handler in the `ControllerPointer`, so that the `fullscreen` mode is toggle.
True by default, can be turned off in the `config.json`.
> Alps 811 fullscreen

- src/controllers/ControllerGyroscope.js
- src/hotspots/Hotspot3D.js
- src/hotspots/HotspotTransform.js
- src/plugin/PluginManager.js
- src/render/RenderManager.js
Various minor patches on master
> Bbaudel master patches

- src/controllers/ControllerBase.js
- src/controllers/ControllerGyroscope.js
- src/controllers/ControllerKeyboard.js
- src/controllers/ControllerManager.js
- src/controllers/ControllerPointer.js
- src/controllers/ControllerType.js
add a type to controllers + a getByType method to the controller manager
> Rroux controllers get by type

- src/controllers/ControllerManager.js
- src/core/Viewer.js
- src/plugin/Plugin.js
- src/plugin/PluginEngine.js
- src/plugin/PluginManager.js
- src/render/view/ViewBase.js
- src/render/view/ViewFlat.js
- src/render/view/ViewGoPro.js
- src/render/view/ViewRectilinear.js
- src/story/Story.js
Fix multiple viewers basic case
> Rroux multiple viewer

- src/camera/Camera.js
- src/render/RenderManager.js
- src/render/shader/ShaderLib.js
Bug: alps-806
Check resolution by launching **multiple-media** sample, setting grid media view to flat.
> Media grid + flat view

- src/3d/Raycaster.js
> Fix the click on mobile with a fake hovered object

- src/camera/CameraAnimation.js
- src/director/Director.js
- src/system/Device.js
- src/timeline/Animation.js
- src/timeline/MetaAnimation.js
- src/timeline/Track.js
- Fix bad timing synchronization in the Director and CameraAnimation.
- Took into account the onSeeked event.
> Alps 587 - Bad sync on director's cut

- src/display/DisplayObject.js
- src/render/RenderManager.js
- src/render/background/BackgroundMeshRenderer.js
Test case : with simple project switch to VR and resize vertically the window.
Known issue: when resizing horizontally viewport is broken.
> Bug 565 - resize canvas in VR display

- Gruntfile.js
- externs/forge/hotspot.ext.js
- reference/hotspot/hotspot-transform-position.json
- reference/hotspot/hotspot-transform.json
- src/audio/Sound.js
- src/camera/Camera.js
- src/hotspots/Hotspot3D.js
- src/hotspots/HotspotAnimation.js
- src/hotspots/HotspotSound.js
- src/hotspots/HotspotStates.js
- src/hotspots/HotspotTransform.js
- src/hotspots/HotspotTransformValues.js
- src/timeline/Animation.js
- src/timeline/MetaAnimation.js
- src/utils/Utils.js
Transform, sound and animation components of the hotspots are now managed by hotspots states.
You can test with new samples hotspots-states-sound and hotspots-states-animation
> Alps 944 hotspots states improvements

- Gruntfile.js
- reference/scene/scene-media-level.json
- reference/scene/scene-media-source.json
- src/3d/Tile.js
- src/camera/Camera.js
- src/controllers/ControllerPointer.js
- src/media/Media.js
- src/media/MediaStore.js
- src/media/MediaTexture.js
- src/render/RenderManager.js
- src/render/background/BackgroundPyramidRenderer.js
- src/render/background/BackgroundRenderer.js
- src/render/background/BackgroundType.js
- src/story/Scene.js
Work in progress with pyramid rendering and quadtree based tiles
> Alps ygilquin multiresolution geometry

- externs/lib/three.ext.js
- reference/hotspot/hotspot-geometry.json
- reference/hotspot/hotspot-material.json
- reference/hotspot/hotspot.json
- src/hotspots/Hotspot3D.js
- src/hotspots/HotspotGeometry.js
- src/hotspots/HotspotManager.js
- src/hotspots/HotspotMaterial.js
- src/hotspots/HotspotStates.js
- src/hotspots/HotspotTransform.js
- src/math/Math.js
- src/render/RenderManager.js
- src/render/RenderPipeline.js
> Rroux editor

- src/3d/PickingDrawPass.js
- src/3d/Raycaster.js
- src/input/Pointer.js
Fix mouse position, please test on dev/projects/div-test
Need to be tested in rectilinear and gopro view
> Alps 1278 mouse position bugfix

- reference/scene/scene-media-events.json
- reference/scene/scene-media.json
- src/media/Media.js
Bim !
Please checkout the sample branch of the same name to test with the media-video-events project
> Add scene media events on json configuration

- Gruntfile.js
- package.json
- reference/hotspot/hotspot-dom.json
- reference/hotspot/hotspot.json
- src/controllers/ControllerManager.js
- src/core/Viewer.js
- src/director/Director.js
- src/display/DisplayObjectContainer.js
- src/hotspots/HotspotDOM.js
- src/hotspots/HotspotManager.js
- src/hotspots/HotspotTransformValues.js
- src/hotspots/HotspotType.js
- src/render/view/ViewManager.js
- src/utils/Utils.js
- test/hotspots/HotspotManager.spec.js
- tools/reference/pages.json
Introduces a first simple DOM hotspot. It got no positioning yet, and it isn't moving when the camera is moving (waiting for a rebase from the master to do that). A DOM hotspot is composed of a DisplayObjectContainer that can contain any other FORGE object which inherits DisplayObject, but also the DOM that can be tweak in any way possible by the user. The FORGE engine is only here to consider the good placement of the main div of the hotspot, without interacting at all in
its inside.
Waiting for Alps 1184 to be resolved before continuing further in this issue.
> Alps 1206 - DOM Hotspots

- src/controllers/ControllerPointer.js
Finally ! Thanks to @bfouet-gpsw
> Add pinch factor correction to controller pointer

- src/hotspots/HotspotDOM.js
- src/system/Device.js
- test/system/Device.spec.js
Improve the device check method + write some tests
> Rroux device check

- src/core/BaseObject.js
- src/media/Media.js
- src/render/RenderManager.js
- patch for Media events checks in Handlers
- patch for console.log display
- patch for possible NaN result into Renderer
> Engine patches

- src/system/Device.js
> fix closure in Device

- src/hotspots/HotspotDOM.js
- src/render/view/ViewGoPro.js
- src/render/view/ViewRectilinear.js
Add visible, interactive and cursor options to the DOM hotspots
> DOM hotspots addons

- reference/controller/controller-options-orientation.json
- src/3d/PickingDrawPass.js
- src/3d/Raycaster.js
- src/controllers/ControllerGyroscope.js
- src/controllers/ControllerPointer.js
- src/input/Pointer.js
Add the drag behaviour to the controller pointer.
Please checkout the other branch with the same name in samples and plugins repos.
You can test it with the controller-pointer sample
> Alps 593 drag to pointer controller

- reference/controller/controller-options-zoom.json
- src/camera/Camera.js
- src/controllers/ControllerPointer.js
WIP
To activate zoom to pointer, use the following controller configuration: 
```json
"controllers":
{
"instances":
[
{
"uid": "pointer",
"type": "pointer",
"options":
{
"zoom": { "invert": false, "toPointer": true }
}
}
]
}
```
> Alps 1293 zoom to pointer 

- src/audio/SoundManager.js
- test/karma.conf.js
- tools/changelog/0.9.4.md
Changelog and small patches for release
> ForgeJS 0.9.4 release

- CONTRIBUTING.md
Update the CONTRIBUTING.md file
> Update md files

- lib/omnitone/omnitone.js
Add omnitone unminifed lib file (0.2.2)
> External library updates

- src/render/view/ViewFlat.js
to test with view-flat sample + Toolbox update
> Change the way ViewFlat handles its repeat options

- src/display/video/VideoDash.js
- src/display/video/VideoHTML5.js
Add playbackrate accessors for VideoHTML5 and VideoDash + onRateChange event
> Alps 310 playback rate

- src/camera/Camera.js
- src/render/background/BackgroundRenderer.js
- src/system/History.js
Fixes multiple bugs, such as:
* `fovMin` wasn't respected when set in a multi resolution scene
* missing `updateUniforms` when in a multi resolution scene
* slug was kept over multiple scenes instead of being cleaned
> Fix multiple bugs

- src/controllers/ControllerManager.js
- src/media/MediaStore.js
- src/render/background/BackgroundPyramidRenderer.js
- src/story/Scene.js
Tried to clean better the texture and tiles in a multi resolution scene. Changed a few things, can be tested in a multi resolution sample with `viewer.destroy()`.
> ALPS-1809 - multiresolution texture cleaning

- src/render/RenderManager.js
- src/render/background/BackgroundRenderer.js
- src/render/postProcessing/ShaderPass.js
Clean non-standard whitespace characters
> Remove non-standard whitespace characters

- src/core/Uid.js
- src/hotspots/HotspotTransform.js
- src/hotspots/HotspotTransformValues.js
- src/story/Story.js
Minor adjustments for editor needs
Please checkout editor-2 from the two other repos samples and plugins
> Hotspot Editor v2

- src/camera/Camera.js
Remove unneeded code, patch max value and clean code
> Minor refactor and patches on Camera class

- reference/viewer/viewer-webgl.json
- reference/viewer/viewer.json
- src/core/Viewer.js
- src/render/RenderManager.js
You can now set options of the webgl context in the viewer json configuration like this 👍 
```
"viewer":
{
"webgl":
{
"preserveDrawingBuffer": true
}
}
```
> Rroux viewer webgl config

- reference/hotspot/hotspot-material.json
- src/hotspots/HotspotGeometry.js
- src/hotspots/HotspotGeometryType.js
- src/hotspots/HotspotMaterial.js
Add a way to set material sides for hotspots and fix the default shape
> Alps 2130 editor geometry

- src/3d/Tile.js
- src/render/background/BackgroundPyramidRenderer.js
Tried to improve somehow the loading of tiles in a multi resolution context. Still not the perfect way, but we're getting there.
> ALPS-1974 - Multiresolution and lookAt

- externs/forge/camera.ext.js
- src/3d/Raycaster.js
- src/camera/Camera.js
- src/controllers/ControllerPointer.js
- src/render/background/BackgroundPyramidRenderer.js
Please checkout the sample branch of the same name :)
> onCameraChange to onChange, + onOrientationChange, + onFovChange

- reference/hotspot/hotspot.json
- src/hotspots/Hotspot3D.js
Just started a PR but do not validate it until the story is complete
> Alps 1975 hotspots scale

- src/camera/Camera.js
Fix some things in Camera with a partial panorama.
Goes with https://github.com/gopro/forgejs-samples/pull/45
> ALPS-1973 - lookat partial panorama

- README.md
- tools/changelog/0.9.5.md
> Alps 0.9.5 release
